spring.datasource.url=jdbc:postgresql://localhost:5432/produto
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cria a tabela produtos se não existir (schema.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
