spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.open-in-view=false

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

jwt.secret=${JWT_SECRET:myjwtsecret}
security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://127.0.0.1:5500,http://localhost:8080}

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.oauth.client-id=${security.client-id}
springdoc.swagger-ui.oauth.client-secret=${security.client-secret}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=false

spring.servlet.multipart.enabled=true
