CREATE TABLE IF NOT EXISTS produtos (
    id         BIGSERIAL PRIMARY KEY,
    nome       VARCHAR(255) NOT NULL UNIQUE,
    preco      DOUBLE PRECISION NOT NULL,
    quantidade INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
    id       BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50) NOT NULL,
    ativo    BOOLEAN NOT NULL DEFAULT TRUE
);
